WebArchiver/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebArchiver.Controllers
{
	public class AboutController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

WebArchiver/Controllers/LastFileController.cs
using Microsoft.AspNetCore.Mvc;
using WebArchiver.Data;
using WebArchiver.Models;

namespace WebArchiver.Controllers
{
	public class LastFileController : Controller
	{
		private readonly ApplicationDBContext _db;
		private readonly int fileCount = 5;

		public LastFileController(ApplicationDBContext db)
		{
			_db = db;
		}
		public IActionResult Index()
		{
			if (User.Identity.IsAuthenticated)
			{
				User loggedUser = _db.User.Where(us => us.Name == User.Identity.Name).ToList().First();

				IQueryable<LastFile> objFilesList = _db.LastFile.Where(u => u.User_id == loggedUser.Id);//.ToList().TakeLast(fileCount).Reverse();
				IEnumerable<LastFile> lf = objFilesList.ToList().TakeLast(fileCount).Reverse();
				return View(lf);
			}
			return RedirectToAction("Login", "Account");
		}
	}
}

WebArchiver/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebArchiver</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebArchiver.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="wrapper">
        <header>
            <div class="header">
                <div class="leftHeader">
                    <img src="../Pictures/helloCatbackgroundless.png">

                    <div class="container">
                        Converter
                        <a asp-area="" asp-controller="Home" asp-action="Index">
                            <span class="link"></span>
                        </a>
                    </div>
                    <div class="container">
                        Last files
                        <a asp-area="" asp-controller="LastFile" asp-action="Index">
                            <span class="link"></span>
                        </a>
                    </div>
                    <div class="container">
                        About
                        <a asp-area="" asp-controller="About" asp-action="Index">
                            <span class="link"></span>
                        </a>
                    </div>
                </div>
                <div class="rightHeader"> 
                    <div class="container" id="login">
                        Log in
                        <a asp-area="" asp-controller="Account" asp-action="Login">
                            <span class="link"></span>
                        </a>
                    </div>
                    <div class="container" id="logout" style="display:none">
                        Log out
                        <a asp-area="" asp-controller="Account" asp-action="LogOut">
                            <span class="link"></span>
                        </a>
                    </div>
                </div>
            </div>
        </header>
        <div class="main">
            <main class="main" role="main">
                @RenderBody()
            </main>
        </div>

        <footer>
            <p>
                Saint-Petersburg state institute of technology (Technological university)
            </p>
            <p>
                2023
            </p>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $(document).ready(function () {
            @{
                if(User.Identity.IsAuthenticated){
                    @:document.getElementById("login").style.display = "none";
                    @:document.getElementById("logout").style.display = "flex";
                }
            }
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>