WebArchiver/Controllers/DownloadController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace WebArchiver.Controllers
{
	public class DownloadController : Controller
	{
		private IWebHostEnvironment _webHostEnvironment;

		public DownloadController(IWebHostEnvironment webHostEnvironment) {
			_webHostEnvironment = webHostEnvironment;
		}
		public IActionResult Index()
		{
			return View("~/Views/Home/Index.cshtml");
		}
		[HttpGet]
		public async Task<IActionResult> SendArchive()
		{
			await Archive();

			String fileDirectory = Path.Combine(_webHostEnvironment.WebRootPath, "UploadFilesDirectory\\UploadFilesDirectory.rar");

			return PhysicalFile(fileDirectory, "application/vnd.rar", "Archive.rar");
		}
		public async Task Archive()
		{
			Process process = new Process();
			String fileDirectory = "ExternalPrograms";
			String batFileDir = Path.Combine(_webHostEnvironment.ContentRootPath, fileDirectory);
			if (!Directory.Exists(batFileDir))
			{
				return;
			}
			String fileName = "ArchiverMVC.bat";
			batFileDir = Path.Combine(batFileDir, fileName);
			process.StartInfo.FileName = batFileDir;
			process.StartInfo.Verb = "runas";
			process.Start();
			
			await process.WaitForExitAsync();
		}
	}
}

WebArchiver/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.Language.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Text;
using WebArchiver.Data;
using WebArchiver.Models;
using System.Web;
using System.Net.Mime;

namespace WebArchiver.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;
		private IWebHostEnvironment _webHostEnvironment;
		private ApplicationDBContext _db;
		private readonly int toKbytes = 1024; 

		[BindProperty, Display(Name = "Drag files here")]
		public List<IFormFile> Uploads { get; set; } = new();

		public HomeController(ILogger<HomeController> logger, IWebHostEnvironment webHostEnvironment, ApplicationDBContext db)
		{
			_logger = logger;
			_webHostEnvironment = webHostEnvironment;
			_db = db;
		}

		public IActionResult Index()
		{
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Upload(IFormFile file)
		{
			String fileDirectory = "UploadFilesDirectory";
			String filePath = Path.Combine(_webHostEnvironment.WebRootPath, fileDirectory);
			String archivePath = Path.Combine(filePath, "UploadFilesDirectory.rar");
			if (Directory.Exists(archivePath))	Directory.Delete(archivePath);

			if (!Directory.Exists(filePath))
			{
				Directory.CreateDirectory(filePath);
			}
			String fileName = file.FileName;
			filePath = Path.Combine(filePath, fileName);

			using (FileStream fs = System.IO.File.Create(filePath)) { await file.CopyToAsync(fs); }

			await AddFilesToDB(file);

			return RedirectToAction("Index");
		}
		public async Task AddFilesToDB(IFormFile file)
		{
			LastFile lf = new LastFile()
			{
				Size = file.Length / toKbytes + 1,
				Name = file.FileName,
				CreatedDateTime = DateTime.Now,
				User_id = 0
			};
			if(User.Identity.IsAuthenticated)
			{
				User loggedUser = _db.User.Where(us => us.Name == User.Identity.Name).ToList().First();
				lf.User_id = loggedUser.Id;
			}
			_db.LastFile.Add(lf);
			await _db.SaveChangesAsync();
		}
		
		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

WebArchiver/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />
<div class="content">
	<div class="converter">
		<h1>
			IZConverter is a small and easy online tool that can compress files, into archives such as 7z, zipx,
			rar, exe and more.
		</h1>
		<h2>

		</h2>
		<form method="post" enctype="multipart/form-data" id="form" data-pasley-validate class="from-horizontal form-label-left">
			<div class="fileDropArea" id="dropzone">
				<div action="/Home/Upload" class="dropzone" id="uploader" style="height:100%; width:100%; background:#d2b087; border:bisque">
					<br />
				</div>
			</div>
		</form>	
		<div class="buttons">
			<form asp-action="SendArchive" asp-controller="Download" method="get">
				<input type="submit" value="Download archive"/> <!-- download -->
			</form>
			<form asp-action="Upload" asp-controller="Home" enctype="multipart/form-data" method="post"> <!-- upload -->
				<input type="file" id="file-button" style="display:none;"/>
				<label for="file-button">Upload from file</label>
				<input type="submit" class="submit_btn"/>
			</form>
		</div>
	</div>
</div>

<script src="~/js/dropzone.min.js"></script>
<script src="~/js/site.js"></script>
<script src="~/js/dragDropHandler.js"></script>